RK-14200 add clear all
Rookout/tutorial-java pull request #50
Opened 2022-10-02 09:43 UTC by hopemanryan

https://rookout.atlassian.net/browse/RK-14200

2022-10-02 12:37 UTC, Urook requested changes

2022-10-02 12:37 UTC, Urook commented on src/main/resources/application.properties
> +opentracing.jaeger.udp-sender.host=localhost
Why?

2022-10-02 12:38 UTC, hopemanryan commented on src/main/resources/application.properties
> +opentracing.jaeger.udp-sender.host=localhost
mmmm was even aware, weird, will revert

2022-10-03 09:48 UTC, Urook approved these changes

2022-10-03 12:34 UTC, merged